CREATE TABLE "dim_tiempo" (
  "id_tiempo" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "anio" integer,
  "mes" varchar(20),
  "dia" varchar(20),
  "rango_hora_3h" varchar(50)
);

CREATE TABLE "dim_geografia" (
  "id_geografia" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo_dane_municipio" varchar(20),
  "municipio" varchar(100),
  "codigo_dane_depto" varchar(20),
  "departamento" varchar(100),
  "zona_hecho" varchar(100),
  "localidad" varchar(100)
);

CREATE TABLE "dim_victima" (
  "id_victima" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sexo" varchar(20),
  "grupo_edad_quinquenal" varchar(50),
  "grupo_mayor_menor_edad" varchar(50),
  "grupo_edad_judicial" varchar(50),
  "ciclo_vital" varchar(50),
  "estado_civil" varchar(50),
  "pais_nacimiento" varchar(100),
  "escolaridad" varchar(100),
  "pertenencia_grupal" varchar(100),
  "pertenencia_etnica" varchar(100),
  "ancestro_racial" varchar(100),
  "pueblo_indigena" varchar(100),
  "orientacion_sexual" varchar(100),
  "identidad_genero" varchar(100),
  "transgenero" varchar(100)
);

CREATE TABLE "dim_circunstancia" (
  "id_circunstancia" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "escenario_hecho" varchar(150),
  "circunstancia_detallada" text,
  "manera_muerte" varchar(100),
  "mecanismo_causal" varchar(150),
  "diagnostico_topografico" text,
  "razon_suicidio" varchar(255)
);

CREATE TABLE "fact_presuntos_suicidios" (
  "id_hecho_original" varchar(50) PRIMARY KEY,
  "id_tiempo" integer NOT NULL,
  "id_geografia" integer NOT NULL,
  "id_victima" integer NOT NULL,
  "id_circunstancia" integer NOT NULL,
  "cantidad" integer DEFAULT 1
);

COMMENT ON COLUMN "dim_tiempo"."anio" IS 'Año del hecho';

COMMENT ON COLUMN "dim_tiempo"."mes" IS 'Mes del hecho';

COMMENT ON COLUMN "dim_tiempo"."dia" IS 'Día del hecho';

COMMENT ON COLUMN "dim_tiempo"."rango_hora_3h" IS 'Rango de Hora del Hecho X 3 Horas';

COMMENT ON COLUMN "dim_geografia"."codigo_dane_municipio" IS 'Código Dane Municipio';

COMMENT ON COLUMN "dim_geografia"."municipio" IS 'Municipio del hecho DANE';

COMMENT ON COLUMN "dim_geografia"."codigo_dane_depto" IS 'Código Dane Departamento';

COMMENT ON COLUMN "dim_geografia"."departamento" IS 'Departamento del hecho DANE';

COMMENT ON COLUMN "dim_geografia"."zona_hecho" IS 'Zona del Hecho (Urbana, Rural, etc.)';

COMMENT ON COLUMN "dim_geografia"."localidad" IS 'Localidad del Hecho';

COMMENT ON COLUMN "dim_victima"."sexo" IS 'Sexo de la victima';

COMMENT ON COLUMN "dim_victima"."grupo_edad_quinquenal" IS 'Grupo de Edad Quinquenal';

COMMENT ON COLUMN "dim_victima"."grupo_mayor_menor_edad" IS 'Grupo Mayor Menor de Edad';

COMMENT ON COLUMN "dim_victima"."grupo_edad_judicial" IS 'Grupo de Edad judicial';

COMMENT ON COLUMN "dim_victima"."ciclo_vital" IS 'Ciclo Vital (Infancia, Juventud, Vejez, etc.)';

COMMENT ON COLUMN "dim_victima"."estado_civil" IS 'Estado Civil';

COMMENT ON COLUMN "dim_victima"."pais_nacimiento" IS 'País de Nacimiento';

COMMENT ON COLUMN "dim_victima"."escolaridad" IS 'Escolaridad';

COMMENT ON COLUMN "dim_victima"."pertenencia_grupal" IS 'Pertenencia Grupal';

COMMENT ON COLUMN "dim_victima"."pertenencia_etnica" IS 'Pertenencia Étnica';

COMMENT ON COLUMN "dim_victima"."ancestro_racial" IS 'Ancestro Racial';

COMMENT ON COLUMN "dim_victima"."pueblo_indigena" IS 'Pueblo Indígena';

COMMENT ON COLUMN "dim_victima"."orientacion_sexual" IS 'Orientación Sexual';

COMMENT ON COLUMN "dim_victima"."identidad_genero" IS 'Identidad de Género';

COMMENT ON COLUMN "dim_victima"."transgenero" IS 'Transgénero';

COMMENT ON COLUMN "dim_circunstancia"."escenario_hecho" IS 'Escenario del Hecho';

COMMENT ON COLUMN "dim_circunstancia"."circunstancia_detallada" IS 'Circunstancia del Hecho Detallada';

COMMENT ON COLUMN "dim_circunstancia"."manera_muerte" IS 'Manera de Muerte';

COMMENT ON COLUMN "dim_circunstancia"."mecanismo_causal" IS 'Mecanismo Causal de la Lesión Fatal';

COMMENT ON COLUMN "dim_circunstancia"."diagnostico_topografico" IS 'Diagnostico Topográfico de la Lesión Fatal';

COMMENT ON COLUMN "dim_circunstancia"."razon_suicidio" IS 'Razón del Suicidio';

COMMENT ON COLUMN "fact_presuntos_suicidios"."id_hecho_original" IS 'ID original del dataset';

COMMENT ON COLUMN "fact_presuntos_suicidios"."cantidad" IS 'Métrica base aditiva para agregaciones';

ALTER TABLE "fact_presuntos_suicidios" ADD FOREIGN KEY ("id_tiempo") REFERENCES "dim_tiempo" ("id_tiempo") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "fact_presuntos_suicidios" ADD FOREIGN KEY ("id_geografia") REFERENCES "dim_geografia" ("id_geografia") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "fact_presuntos_suicidios" ADD FOREIGN KEY ("id_victima") REFERENCES "dim_victima" ("id_victima") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "fact_presuntos_suicidios" ADD FOREIGN KEY ("id_circunstancia") REFERENCES "dim_circunstancia" ("id_circunstancia") DEFERRABLE INITIALLY IMMEDIATE;
